### ISSUE TITLE
"Load Error: Cannot load such file" cuando ejecuto el require

### ISSUE THREAD

**Issue by monpac** [TodoPago/SDK-Ruby#4]
```bash
irb(main):001:0> require 'todo_pago_conector'
LoadError: cannot load such file -- rest-client
	from ~/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from ~/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/TodoPagoConector-1.1.0/lib/todo_pago_conector.rb:2:in `<top (required)>'
	from ~/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from ~/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from ~/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from (irb):1
	from ~/.rbenv/versions/2.2.3/bin/irb:11:in `<main>'
```

Estoy usando una versión no compatible con la librería?

**Comment by damianwajser** [comment]
vamos a introducir la corrección (tanto en la documentación como en la creación de la gema), pero para que funcione de momento ingresa este comando: "gem install rest-client".
Muchas Gracias!

**Comment by monpac** [comment]
Gracias! Funcionó
